name: repro
on: [push]
jobs:
  repro:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Download nvda-portable zip
        uses: robinraju/release-downloader@v1.9
        id: nvda-portable-download
        with:
          repository: "bocoup/aria-at-automation-nvda-builds"
          tarBall: false
          zipBall: false
          tag: '2023.3'
          latest: false
          out-file-path: "nvda-portable"
          extract: false

      - name: Run harness
        shell: powershell
        timeout-minutes: 30
        env:
          NVDA_PORTABLE_ZIP: ${{ fromJson(steps.nvda-portable-download.outputs.downloaded_files)[0] }}
        run: |
          & .\run-chrome.ps1

      - name: upload logs and screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: |
            D:\a\chromedriver-blank-window-demonstration\chromedriver-blank-window-demonstration\*-log.txt
            D:\a\chromedriver-blank-window-demonstration\chromedriver-blank-window-demonstration\*.png
